### PR TITLE
feat: Change web base url when restoring database

### PR DESCRIPTION
**Pull request by BonnetAdam**
Fix this issues #21

### CODE REVIEW

**Comment by BurkhalterY** [comment]
I think it's less risky to delete key = web.base.url.freeze instead.
Because the base URL is not localhost through the Docker. Deleting web.base.url.freeze will ask Odoo to recompute the base URL.

**Comment by remyz17** [comment]
someone know why the workflows don't run correctly ? looks like there is problems when checking out @BonnetAdam branch

**Comment by BonnetAdam** [comment]
> someone know why the workflows don't run correctly ? looks like there is problems when checking out @BonnetAdam branch

I think it's due that the source repo is BonnetAdam/odooghost and not remyz17/odooghost ... Since it's a fork

**Comment by BurkhalterY** [comment]
I fixed the previous git fetch error, but I think the current one requires changes on repo configuration...

I let you check

**Pull request merged**
